export const ActionTypes = {
  SET_POSTS: "SET_POSTS",
  SET_SINGLE_POST: "SET_SINGLE_POST",
  REMOVE_SINGLE_POST_FROM_STATE: "REMOVE_SINGLE_POST_FROM_STATE",
  SET_USERS: "SET_USERS",
  GET_USERS: "GET_USERS",
  REMOVE_USERS: "REMOVE_USERS",
  GET_USERS_REQUESTED: "GET_USERS_REQUESTED",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILED: "GET_USERS_FAILED",
  GET_POSTS_REQUESTED: "GET_POSTS_REQUESTED",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAILED: "GET_POSTS_FAILED",
};
